### ISSUE TITLE
Dont't Support for jdk10 ?

### ISSUE THREAD

**Issue by CaiJiJi** [vysec/ANGRYPUPPY#8]
![kk](https://user-images.githubusercontent.com/10561685/43209006-439dc602-905e-11e8-9528-337f13825287.png)

**Comment by 001SPARTaN** [comment]
Cobalt Strike does not support Java 10, so this is not an issue with ANGRYPUPPY itself.

**Comment by CaiJiJi** [comment]
I use cobaltstrike 3.11 need jdk10

**Comment by dcsync** [comment]
Hey, I ran into the same issue while trying to use json.jar for something. The issue is [present in jdk9+](https://community.oracle.com/message/14206675#14206675).

Here's my solution if anyone's interested in adapting it for ANGRYPUPPY: https://github.com/dcsync/pycobalt/blob/master/aggressor/json.cna#L21

**Comment by dcsync** [comment]
Here's an untested patch https://github.com/dcsync/ANGRYPUPPY/commit/0004b04275b5ac25366721e9196e18853e054cf2. I should have a chance to test it next week.
